import { CreateBookInput } from '../create/types/input'

/**
 * Demo catalogue loaded by the seed endpoint.
 *
 * Titles and authors are real; the ISBN codes are made up (they do carry a
 * valid ISBN-13 check digit) except for the four software titles, which use
 * their published code. Every book is seeded with `sellingPriceLocal: null`,
 * so `POST /books/{id}/calculate-price` still has something to compute.
 */
export const SEED_BOOKS: CreateBookInput[] = [
  {
    title: 'Don Quijote de la Mancha',
    author: 'Miguel de Cervantes',
    isbn: '9788432884719',
    costUsd: 18.5,
    stockQuantity: 24,
    category: 'Literatura Clásica',
    supplierCountry: 'ES',
  },
  {
    title: 'Cien años de soledad',
    author: 'Gabriel García Márquez',
    isbn: '9789589502938',
    costUsd: 16.99,
    stockQuantity: 31,
    category: 'Realismo Mágico',
    supplierCountry: 'CO',
  },
  {
    title: 'La casa de los espíritus',
    author: 'Isabel Allende',
    isbn: '9789569873133',
    costUsd: 15.4,
    stockQuantity: 18,
    category: 'Realismo Mágico',
    supplierCountry: 'CL',
  },
  {
    title: 'Rayuela',
    author: 'Julio Cortázar',
    isbn: '9789509603608',
    costUsd: 17.25,
    stockQuantity: 12,
    category: 'Ficción Contemporánea',
    supplierCountry: 'AR',
  },
  {
    title: 'Pedro Páramo',
    author: 'Juan Rulfo',
    isbn: '9786075323817',
    costUsd: 11.8,
    stockQuantity: 27,
    category: 'Realismo Mágico',
    supplierCountry: 'MX',
  },
  {
    title: 'Ficciones',
    author: 'Jorge Luis Borges',
    isbn: '9789507630521',
    costUsd: 13.6,
    stockQuantity: 9,
    category: 'Ficción Contemporánea',
    supplierCountry: 'AR',
  },
  {
    title: 'La ciudad y los perros',
    author: 'Mario Vargas Llosa',
    isbn: '9786128547085',
    costUsd: 14.95,
    stockQuantity: 15,
    category: 'Ficción Contemporánea',
    supplierCountry: 'PE',
  },
  {
    title: 'El amor en los tiempos del cólera',
    author: 'Gabriel García Márquez',
    isbn: '9789586584623',
    costUsd: 16.5,
    stockQuantity: 21,
    category: 'Realismo Mágico',
    supplierCountry: 'CO',
  },
  {
    title: 'Como agua para chocolate',
    author: 'Laura Esquivel',
    isbn: '9786070997112',
    costUsd: 12.3,
    stockQuantity: 8,
    category: 'Ficción Contemporánea',
    supplierCountry: 'MX',
  },
  {
    title: 'Doña Bárbara',
    author: 'Rómulo Gallegos',
    isbn: '9789803504670',
    costUsd: 10.75,
    stockQuantity: 40,
    category: 'Literatura Clásica',
    supplierCountry: 'VE',
  },
  {
    title: 'Las lanzas coloradas',
    author: 'Arturo Uslar Pietri',
    isbn: '9789806990609',
    costUsd: 9.9,
    stockQuantity: 6,
    category: 'Literatura Clásica',
    supplierCountry: 'VE',
  },
  {
    title: 'La vorágine',
    author: 'José Eustasio Rivera',
    isbn: '9789582199098',
    costUsd: 11.2,
    stockQuantity: 14,
    category: 'Literatura Clásica',
    supplierCountry: 'CO',
  },
  {
    title: 'Martín Fierro',
    author: 'José Hernández',
    isbn: '9789500233750',
    costUsd: 8.5,
    stockQuantity: 19,
    category: 'Poesía',
    supplierCountry: 'AR',
  },
  {
    title: 'Veinte poemas de amor y una canción desesperada',
    author: 'Pablo Neruda',
    isbn: '9789565936788',
    costUsd: 9.75,
    stockQuantity: 23,
    category: 'Poesía',
    supplierCountry: 'CL',
  },
  {
    title: 'Romancero gitano',
    author: 'Federico García Lorca',
    isbn: '9788453158356',
    costUsd: 10.4,
    stockQuantity: 7,
    category: 'Poesía',
    supplierCountry: 'ES',
  },
  {
    title: 'Nada',
    author: 'Carmen Laforet',
    isbn: '9788488847591',
    costUsd: 12.6,
    stockQuantity: 11,
    category: 'Literatura Clásica',
    supplierCountry: 'ES',
  },
  {
    title: 'La sombra del viento',
    author: 'Carlos Ruiz Zafón',
    isbn: '9788431995607',
    costUsd: 19.9,
    stockQuantity: 26,
    category: 'Misterio',
    supplierCountry: 'ES',
  },
  {
    title: 'El túnel',
    author: 'Ernesto Sabato',
    isbn: '9789508512611',
    costUsd: 10.1,
    stockQuantity: 5,
    category: 'Ficción Contemporánea',
    supplierCountry: 'AR',
  },
  {
    title: 'Los detectives salvajes',
    author: 'Roberto Bolaño',
    isbn: '9789560794826',
    costUsd: 21.4,
    stockQuantity: 13,
    category: 'Ficción Contemporánea',
    supplierCountry: 'CL',
  },
  {
    title: '1984',
    author: 'George Orwell',
    isbn: '9780079809711',
    costUsd: 14.99,
    stockQuantity: 35,
    category: 'Ciencia Ficción',
    supplierCountry: 'GB',
  },
  {
    title: 'Un mundo feliz',
    author: 'Aldous Huxley',
    isbn: '9780038828319',
    costUsd: 13.5,
    stockQuantity: 22,
    category: 'Ciencia Ficción',
    supplierCountry: 'GB',
  },
  {
    title: 'Fahrenheit 451',
    author: 'Ray Bradbury',
    isbn: '9781747440458',
    costUsd: 13.25,
    stockQuantity: 17,
    category: 'Ciencia Ficción',
    supplierCountry: 'US',
  },
  {
    title: 'Dune',
    author: 'Frank Herbert',
    isbn: '9781086063837',
    costUsd: 22.75,
    stockQuantity: 20,
    category: 'Ciencia Ficción',
    supplierCountry: 'US',
  },
  {
    title: 'Fundación',
    author: 'Isaac Asimov',
    isbn: '9781845559588',
    costUsd: 15.8,
    stockQuantity: 10,
    category: 'Ciencia Ficción',
    supplierCountry: 'US',
  },
  {
    title: 'El señor de los anillos',
    author: 'J. R. R. Tolkien',
    isbn: '9780937669136',
    costUsd: 39.99,
    stockQuantity: 16,
    category: 'Fantasía',
    supplierCountry: 'GB',
  },
  {
    title: 'El hobbit',
    author: 'J. R. R. Tolkien',
    isbn: '9780821095089',
    costUsd: 18.75,
    stockQuantity: 28,
    category: 'Fantasía',
    supplierCountry: 'GB',
  },
  {
    title: 'Harry Potter y la piedra filosofal',
    author: 'J. K. Rowling',
    isbn: '9780402823179',
    costUsd: 20.5,
    stockQuantity: 44,
    category: 'Fantasía',
    supplierCountry: 'GB',
  },
  {
    title: 'Juego de tronos',
    author: 'George R. R. Martin',
    isbn: '9781439964750',
    costUsd: 24.9,
    stockQuantity: 19,
    category: 'Fantasía',
    supplierCountry: 'US',
  },
  {
    title: 'El nombre del viento',
    author: 'Patrick Rothfuss',
    isbn: '9781706068334',
    costUsd: 23.6,
    stockQuantity: 4,
    category: 'Fantasía',
    supplierCountry: 'US',
  },
  {
    title: 'Crimen y castigo',
    author: 'Fiódor Dostoyevski',
    isbn: '9785487750549',
    costUsd: 17.4,
    stockQuantity: 12,
    category: 'Literatura Clásica',
    supplierCountry: 'RU',
  },
  {
    title: 'Anna Karénina',
    author: 'León Tolstói',
    isbn: '9785224357321',
    costUsd: 19.25,
    stockQuantity: 9,
    category: 'Literatura Clásica',
    supplierCountry: 'RU',
  },
  {
    title: 'Orgullo y prejuicio',
    author: 'Jane Austen',
    isbn: '9780254143029',
    costUsd: 12.95,
    stockQuantity: 30,
    category: 'Literatura Clásica',
    supplierCountry: 'GB',
  },
  {
    title: 'Matar a un ruiseñor',
    author: 'Harper Lee',
    isbn: '9781028379668',
    costUsd: 15.5,
    stockQuantity: 18,
    category: 'Ficción Contemporánea',
    supplierCountry: 'US',
  },
  {
    title: 'El gran Gatsby',
    author: 'F. Scott Fitzgerald',
    isbn: '9781599712703',
    costUsd: 11.9,
    stockQuantity: 25,
    category: 'Literatura Clásica',
    supplierCountry: 'US',
  },
  {
    title: 'El viejo y el mar',
    author: 'Ernest Hemingway',
    isbn: '9781790375431',
    costUsd: 9.5,
    stockQuantity: 33,
    category: 'Literatura Clásica',
    supplierCountry: 'US',
  },
  {
    title: 'La metamorfosis',
    author: 'Franz Kafka',
    isbn: '9783682245570',
    costUsd: 8.2,
    stockQuantity: 3,
    category: 'Literatura Clásica',
    supplierCountry: 'DE',
  },
  {
    title: 'El principito',
    author: 'Antoine de Saint-Exupéry',
    isbn: '9782651858759',
    costUsd: 12.4,
    stockQuantity: 52,
    category: 'Infantil',
    supplierCountry: 'FR',
  },
  {
    title: 'Asesinato en el Orient Express',
    author: 'Agatha Christie',
    isbn: '9780831259914',
    costUsd: 14.3,
    stockQuantity: 15,
    category: 'Misterio',
    supplierCountry: 'GB',
  },
  {
    title: 'El código Da Vinci',
    author: 'Dan Brown',
    isbn: '9781815559518',
    costUsd: 16.8,
    stockQuantity: 7,
    category: 'Misterio',
    supplierCountry: 'US',
  },
  {
    title: 'Sapiens: De animales a dioses',
    author: 'Yuval Noah Harari',
    isbn: '9789652367518',
    costUsd: 25.99,
    stockQuantity: 29,
    category: 'Historia',
    supplierCountry: 'IL',
  },
  {
    title: 'Breve historia del tiempo',
    author: 'Stephen Hawking',
    isbn: '9780001410732',
    costUsd: 18.9,
    stockQuantity: 14,
    category: 'Ciencia',
    supplierCountry: 'GB',
  },
  {
    title: 'El gen egoísta',
    author: 'Richard Dawkins',
    isbn: '9780418899823',
    costUsd: 21.5,
    stockQuantity: 6,
    category: 'Ciencia',
    supplierCountry: 'GB',
  },
  {
    title: 'Pensar rápido, pensar despacio',
    author: 'Daniel Kahneman',
    isbn: '9781082008702',
    costUsd: 26.4,
    stockQuantity: 11,
    category: 'Negocios',
    supplierCountry: 'US',
  },
  {
    title: 'El hombre en busca de sentido',
    author: 'Viktor Frankl',
    isbn: '9783886055272',
    costUsd: 13.75,
    stockQuantity: 21,
    category: 'Filosofía',
    supplierCountry: 'AT',
  },
  {
    title: 'Meditaciones',
    author: 'Marco Aurelio',
    isbn: '9788888449647',
    costUsd: 10.6,
    stockQuantity: 8,
    category: 'Filosofía',
    supplierCountry: 'IT',
  },
  {
    title: 'Así habló Zaratustra',
    author: 'Friedrich Nietzsche',
    isbn: '9783718119714',
    costUsd: 14.2,
    stockQuantity: 2,
    category: 'Filosofía',
    supplierCountry: 'DE',
  },
  {
    title: 'Clean Code',
    author: 'Robert C. Martin',
    isbn: '9780132350884',
    costUsd: 42.5,
    stockQuantity: 13,
    category: 'Software Engineering',
    supplierCountry: 'US',
  },
  {
    title: 'Clean Architecture',
    author: 'Robert C. Martin',
    isbn: '9780134494166',
    costUsd: 38.99,
    stockQuantity: 9,
    category: 'Software Engineering',
    supplierCountry: 'US',
  },
  {
    title: 'The Pragmatic Programmer',
    author: 'David Thomas',
    isbn: '9780135957059',
    costUsd: 44.25,
    stockQuantity: 5,
    category: 'Software Engineering',
    supplierCountry: 'US',
  },
  {
    title: 'Design Patterns',
    author: 'Erich Gamma',
    isbn: '9780201633610',
    costUsd: 54.9,
    stockQuantity: 3,
    category: 'Software Engineering',
    supplierCountry: 'US',
  },
]
